spring:
  application:
    name: cloud-config-server
  
  cloud:
    config:
      server:
        git:
          uri: file:///D:/JvmProjects/git-localconfig-repo
          
  zipkin:
    base-url: http://localhost:9411/
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    
server:
  port: 8888