spring:
  application:
    name: cloud-config-server
  
  cloud:
    config:
      server:
        git:
          uri: ${SPRING.CLOUD.CONFIG.SERVER.GIT.URI}
          skip-ssl-validation: true
                    
  zipkin:
    base-url: ${SPRING.ZIPKIN.BASE_URL}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}
    
server:
  port: 8888