spring:
  application:
    name: api-gateway

  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
   
  zipkin:
    base-url: ${SPRING.ZIPKIN.BASE_URL}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}
    
server:
  port: 8765
