spring:
  application:
    name: currency-conversion
    
#  config:
#    import: ${SPRING.CONFIG.IMPORT}
    
  zipkin:
    base-url: ${SPRING.ZIPKIN.BASE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}
      
server:
  port: 8100