spring:
  application:
    name: eureka-server
    
  cloud:
    config:
      enabled: false
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
server:
  port: 8761
