spring:
  application:
    name: currency-exchange
    
  config:
    import: optional:configserver:http://localhost:8888
      
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5
  ratelimiter:
    instances:
      default: 
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
      
    
server:
  port: 8000