spring:
  application:
    name: currency-exchange
    
#  config:
#    import: ${SPRING.CONFIG.IMPORT}
      
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      
  zipkin:
    base-url: ${SPRING.ZIPKIN.BASE_URL}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}
      
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5
  ratelimiter:
    instances:
      default: 
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
      
    
server:
  port: 8000